---
# ============================================================================ #
# File   : site.yaml                                                           #
# Purpose: Playbook to ensure all servers in the inventory are managed by      #
#          Ansible. And ensures that custom facts are set.                     #
#                                                                              #
# Author : Harald van der Laan                                                 #
# Date   : 2020-09-10                                                          #
# Version: v1.0.0                                                              #
# ============================================================================ #
# Changelog:                                                                   #
# - v1.0.0: initial commit                               (Harald van der Laan) #
# ============================================================================ #
# Copyright © 2020 Harald van der Laan                                         #
#                                                                              #
# Permission is hereby granted, free of charge, to any person obtaining        #
# a copy of this software and associated documentation files (the "Software"), #
# to deal in the Software without restriction, including without limitation    #
# the rights to use, copy, modify, merge, publish, distribute, sublicense,     #
# and/or sell copies of the Software, and to permit persons to whom the        #
# Software is furnished to do so, subject to the following conditions:         #
#                                                                              #
# The above copyright notice and this permission notice shall be included      #
# in all copies or substantial portions of the Software.                       #
#                                                                              #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,              #
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES              #
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.    #
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,  #
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,                #
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE   #
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                #
# ============================================================================ #

- hosts: all
  gather_facts: true

  # For this playbook administrative permissions are required. These permissions
  # are required for all steps in this playbook. Therefor we place become at
  # the beginning of this playbook, normaily we should do this only per task
  # when needed.
  become: true

  tasks:
    - block:
      # This named task will ensure that the directory for custom/local facts is
      # present on the remote target. when this is not the case it will create it.
      - name: facts -> ensure /etc/ansible/facts.d is present
        file:
          path: /etc/ansible/facts.d
          state: directory
        register: factsdir

      # This named task will use the stat module to find out if the custom/local
      # facts file /etc/ansible/facts.d/ansible.facts exists
      - name: facts -> checking if /etc/ansible/facts.d/ansible.facts exists
        stat:
          path: /etc/ansible/facts.d/ansible.fact
        register: factsfile

    # named task for creating custom/local fact file when it not exists
    - name: facts -> create custom/local facts file
      file:
        path: /etc/ansible/facts.d/ansible.fact
        state: touch
      when: factsdir.changed or factsfile.stat.exists == "False"
      register: createfactsfile

    # named task for getting all facts after creating the facts file
    - name: facts -> updating facts after changes
      setup:
      when: createfactsfile.changed

    # including role ansible-bootstrap for bootstrapping remote targets so
    # they can you ansible as management tool. for more information about this
    # role please read the readme.md in roles/ansible-bootstrap.
    - name: role -> including role ansible-bootstrap
      include_role:
        name: ansible-bootstrap
      when: createfactsfile.changed

    # including the bootstrap role to deploy custom setting on a server. and
    # insure the baseline is the same on all servers
    - name: role -> include role bootstrap
      include_role:
        name: bootstrap
