# ============================================================================ #
# File   : roles/firewall/defaults/main.yaml                                   #
# Purpose: Configuration defaults for the firewall role                        #
#                                                                              #
# Author : Harald van der Laan                                                 #
# Date   : 2022-04-19                                                          #
# Version: v1.0.0                                                              #
# ============================================================================ #
# Changelog:                                                                   #
# - v1.0.0: Initiak version                              (Harald van der Laan) #
# ============================================================================ #
# Copyright © 2022 Harald van der Laan                                         #
#                                                                              #
# Permission is hereby granted, free of charge, to any person obtaining        #
# a copy of this software and associated documentation files (the "Software"), #
# to deal in the Software without restriction, including without limitation    #
# the rights to use, copy, modify, merge, publish, distribute, sublicense,     #
# and/or sell copies of the Software, and to permit persons to whom the        #
# Software is furnished to do so, subject to the following conditions:         #
#                                                                              #
# The above copyright notice and this permission notice shall be included      #
# in all copies or substantial portions of the Software.                       #
#                                                                              #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,              #
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES              #
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.    #
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,  #
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,                #
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE   #
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                #
# ============================================================================ #

# default ufw policy is deny
policy: deny

# ip whitelisting from ip to any
whitelist:
  - 82.161.239.68     # old xs4all ip
  - 77.174.189.117    # new xs4all ip

# ip blacklisting deny any
blacklist:
  - 91.191.209.123
  - 141.98.10.40
  - 78.128.113.119
  - 156.96.119.44
  - 45.150.206.113

# opening service ports 
services:
  - port: 25
    proto: any
  - port: 80
    proto: any
  - port: 110
    proto: any
  - port: 143
    proto: any
  - port: 443
    proto: any
  - port: 465
    proto: any
  - port: 587
    proto: any
  - port: 993
    proto: any
  - port: 995
    proto: any
  - port: 3443
    proto: any
  - port: 5222
    proto: any
  - port: 5223
    proto: any
  - port: 9071
    proto: tcp
