---
# ============================================================================ #
# File   : roles/weeklypatching/tasks/RedHat.yaml                              #
# Purpose: running weeklypatching on RedHat based systems                      #
#                                                                              #
# Author : Harald van der Laan                                                 #
# Date   : 2022-04-19                                                          #
# Version: v1.0.1                                                              #
# ============================================================================ #
# Changelog:                                                                   #
# - v1.0.1: correct syntax error                         (Harald van der Laan) #
# - v1.0.0: Initial commit                               (Harald van der Laan) #
# ============================================================================ #
# Copyright © 2020 Harald van der Laan                                         #
#                                                                              #
# Permission is hereby granted, free of charge, to any person obtaining        #
# a copy of this software and associated documentation files (the "Software"), #
# to deal in the Software without restriction, including without limitation    #
# the rights to use, copy, modify, merge, publish, distribute, sublicense,     #
# and/or sell copies of the Software, and to permit persons to whom the        #
# Software is furnished to do so, subject to the following conditions:         #
#                                                                              #
# The above copyright notice and this permission notice shall be included      #
# in all copies or substantial portions of the Software.                       #
#                                                                              #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,              #
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES              #
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.    #
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,  #
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,                #
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE   #
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                #
# ============================================================================ #

# This is a RedHat based os specific platbook and should run only on RedHat
# based systems

# updating yum repository's
- name: yum -> update repository's
  ansible.builtin.yum:
    update_cache: true
    cacje_valid_time: 86400

# running yum to download end install the latest patches
- name: yum -> download and install latest patches
  ansible.builtin.yum:
    name: "*"
    state: latest